apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2024-05-06T16:51:02Z"
    generation: 1
    labels:
      app: node-app
    name: node-app
    namespace: default
    resourceVersion: "3639"
    uid: ff34c273-a0bb-400c-b85b-f1d1eefeb81b
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: node-app
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: node-app
      spec:
        containers:
        - image: aymendr/numeric-app:0da02eef2c4d72941b0d14494f356b37d422e836
          imagePullPolicy: IfNotPresent
          name: numeric-app
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    conditions:
    - lastTransitionTime: "2024-05-06T16:51:02Z"
      lastUpdateTime: "2024-05-06T16:51:02Z"
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: Available
    - lastTransitionTime: "2024-05-06T16:51:02Z"
      lastUpdateTime: "2024-05-06T16:51:02Z"
      message: ReplicaSet "node-app-7bdd6c76f5" is progressing.
      reason: ReplicaSetUpdated
      status: "True"
      type: Progressing
    observedGeneration: 1
    replicas: 1
    unavailableReplicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
